### ISSUE TITLE
undefined reference to `POWER_SetVoltageForFreq'

### ISSUE THREAD

**Issue by marcbressler** [platformio/platform-nxplpc#12]
OS: Windows 10 x64
PlatformIO IDE + NXP LPC installed

When I attempt to build the following simple program:

```
#include <mbed.h>

int main() {
    DigitalOut led1(LED1);

    while(true) {
      led1 = !led1;
      wait(1);
    }
}
```

I get the following log output and error:

```
[06/12/18 17:37:11] Processing lpc54114 (platform: nxplpc; board: lpc54114; framework: mbed)
 
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: NXP LPC > NXP LPCXpresso54114
SYSTEM: LPC54114J256BD64 100MHz 192KB RAM (256KB Flash)
DEBUG: CURRENT(cmsis-dap) ON-BOARD(cmsis-dap) EXTERNAL(jlink)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 15 compatible libraries
Scanning dependencies...
No dependencies
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\AnalogIn.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\BusIn.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\BusInOut.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\BusOut.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\CAN.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\Ethernet.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\FlashIAP.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\I2C.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\I2CSlave.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\InterruptIn.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\InterruptManager.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\MbedCRC.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\RawSerial.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\SPI.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\SPISlave.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\Serial.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\SerialBase.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\TableCRC.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\Ticker.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\Timeout.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\Timer.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\TimerEvent.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\drivers\UARTSerial.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_critical_section_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_flash_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_gpio.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_itm_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_lp_ticker_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_pinmap_common.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_sleep_manager.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_ticker_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\hal\mbed_us_ticker_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\ATCmdParser.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\CallChain.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\FileBase.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\FileHandle.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\FilePath.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\FileSystemHandle.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\LocalFileSystem.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\Stream.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_alloc_wrappers.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_application.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_assert.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_board.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_critical.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_error.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_interface.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_mem_trace.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_mktime.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_poll.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_retarget.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_rtc_time.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_sdk_boot.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_semihost_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_stats.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_wait_api_no_rtos.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\platform\mbed_wait_api_rtos.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso\PeripheralPins.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso\clock_config.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso\mbed_overrides.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\device\TARGET_LPC54114_M4\TOOLCHAIN_GCC_ARM\startup_LPC54114_cm4.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\device\TARGET_LPC54114_M4\system_LPC54114_cm4.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_adc.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_clock.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_common.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_crc.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_ctimer.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_dma.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_dmic.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_dmic_dma.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_flashiap.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_flexcomm.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_fmeas.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_gint.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_gpio.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2c.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2c_dma.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2s.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2s_dma.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_inputmux.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_mrt.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_pint.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_power.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_reset.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_rtc.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_sctimer.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_spi.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_spi_dma.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_usart.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_usart_dma.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_utick.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_wwdt.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\analogin_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\flash_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\gpio_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\gpio_irq_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\i2c_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\pinmap.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\port_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\rtc_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\serial_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.o
In file included from C:\Users\mbressler\.platformio\packages\framework-mbed\hal/sleep_api.h:22:0,
from C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c:16:
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c: In function 'hal_deepsleep':
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso/device.h:32:32: warning: statement with no effect [-Wun
used-value]
#define LPC_CLOCK_INTERNAL_IRC BOARD_BootClockFRO12M
^
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c:29:5: note: in expansion of macro 'LPC_CLOCK_INTERNAL_IRC'
LPC_CLOCK_INTERNAL_IRC;
^~~~~~~~~~~~~~~~~~~~~~
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso/device.h:33:32: warning: statement with no effect [-Wun
used-value]
#define LPC_CLOCK_RUN          BOARD_BootClockFROHF48M
^
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c:32:5: note: in expansion of macro 'LPC_CLOCK_RUN'
LPC_CLOCK_RUN;
^~~~~~~~~~~~~
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\spi_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\trng_api.o
Compiling .pioenvs\lpc54114\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\us_ticker.o
Compiling .pioenvs\lpc54114\src\main.o
Generating LD script .pioenvs\lpc54114\LPC54114J256_cm4_flash.ld.link_script.ld
Linking .pioenvs\lpc54114\firmware.elf
.pioenvs/lpc54114/FrameworkMbedCore/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/TARGET_LPCXpresso/clock_config.o: In function `BOARD_BootClockFROHF48M':
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso/clock_config.c:130: undefined reference to `POWER_SetVo
ltageForFreq'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\lpc54114\firmware.elf] Error 1
 [ERROR] Took 26.26 seconds
```

What is strange is that I have confirmed that the reference  `POWER_SetVoltageForFreq` in `clock_config.c` is present in the included `fsl_power.h` as `void POWER_SetVoltageForFreq(uint32_t freq)`.

**Comment by valeros** [comment]
Hi @marcbressler! Should be fixed in the dev branch. Please retest with http://docs.platformio.org/en/latest/platforms/nxplpc.html#upstream

**Comment by ivankravets** [comment]
Fixed in the latest release. Please `pio update`.

**Comment by marcbressler** [comment]
After running `pio update` and `pio upgrade`, using the following platformio.ini:
```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

; [env:lpc54114]
; platform = nxplpc
; board = lpc54114
; framework = mbed
; upload_port = COM3

[env:upstream_develop]
platform = https://github.com/platformio/platform-nxplpc.git
board = lpc54114
framework = mbed
upload_port = COM3
```

I get the following errors still

```
[06/19/18 10:58:01] Processing upstream_develop (platform: https://github.com/platformio/platform-nxplpc.git; board: lpc54114; framework: mbed)
 
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: NXP LPC > NXP LPCXpresso54114
SYSTEM: LPC54114J256BD64 100MHz 192KB RAM (256KB Flash)
DEBUG: CURRENT(cmsis-dap) ON-BOARD(cmsis-dap) EXTERNAL(jlink)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf

LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 15 compatible libraries
Scanning dependencies...
No dependencies
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\AnalogIn.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\BusIn.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\BusInOut.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\BusOut.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\CAN.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\Ethernet.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\FlashIAP.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\I2C.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\I2CSlave.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\InterruptIn.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\InterruptManager.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\MbedCRC.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\RawSerial.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\SPI.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\SPISlave.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\Serial.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\SerialBase.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\TableCRC.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\Ticker.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\Timeout.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\Timer.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\TimerEvent.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\drivers\UARTSerial.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_critical_section_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_flash_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_gpio.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_itm_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_lp_ticker_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_pinmap_common.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_sleep_manager.o

Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_ticker_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\hal\mbed_us_ticker_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\ATCmdParser.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\CallChain.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\FileBase.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\FileHandle.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\FilePath.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\FileSystemHandle.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\LocalFileSystem.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\Stream.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_alloc_wrappers.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_application.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_assert.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_board.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_critical.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_error.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_interface.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_mem_trace.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_mktime.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_poll.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_retarget.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_rtc_time.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_sdk_boot.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_semihost_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_stats.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_wait_api_no_rtos.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\platform\mbed_wait_api_rtos.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso\PeripheralPins.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso\clock_config.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso\mbed_overrides.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\device\TARGET_LPC54114_M4\TOOLCHAIN_GCC_ARM\startup_LPC54114_cm4.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\device\TARGET_LPC54114_M4\system_LPC54114_cm4.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_adc.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_clock.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_common.o

Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_crc.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_ctimer.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_dma.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_dmic.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_dmic_dma.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_flashiap.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_flexcomm.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_fmeas.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_gint.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_gpio.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2c.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2c_dma.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2s.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_i2s_dma.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_inputmux.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_mrt.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_pint.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_power.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_reset.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_rtc.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_sctimer.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_spi.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_spi_dma.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_usart.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_usart_dma.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_utick.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\drivers\fsl_wwdt.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\analogin_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\flash_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\gpio_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\gpio_irq_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\i2c_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\pinmap.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\port_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\rtc_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\serial_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.o
In file included from C:\Users\mbressler\.platformio\packages\framework-mbed\hal/sleep_api.h:22:0,
from C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c:16:

C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c: In function 'hal_deepsleep':
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso/device.h:32:32: warning: statement with no effect [-Wunused-va
lue]
#define LPC_CLOCK_INTERNAL_IRC BOARD_BootClockFRO12M
^
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c:29:5: note: in expansion of macro 'LPC_CLOCK_INTERNAL_IRC'
LPC_CLOCK_INTERNAL_IRC;
^~~~~~~~~~~~~~~~~~~~~~
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC54114\TARGET_LPCXpresso/device.h:33:32: warning: statement with no effect [-Wunused-va
lue]
#define LPC_CLOCK_RUN          BOARD_BootClockFROHF48M
^
C:\Users\mbressler\.platformio\packages\framework-mbed\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\sleep.c:32:5: note: in expansion of macro 'LPC_CLOCK_RUN'
LPC_CLOCK_RUN;
^~~~~~~~~~~~~
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\spi_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\trng_api.o
Compiling .pioenvs\upstream_develop\FrameworkMbedCore\targets\TARGET_NXP\TARGET_MCUXpresso_MCUS\TARGET_LPC\us_ticker.o
Compiling .pioenvs\upstream_develop\src\main.o
Generating LD script .pioenvs\upstream_develop\LPC54114J256_cm4_flash.ld.link_script.ld
Linking .pioenvs\upstream_develop\firmware.elf
Checking size .pioenvs\upstream_develop\firmware.elf
Building .pioenvs\upstream_develop\firmware.bin
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [          ]   1.4% (used 2840 bytes from 196608 bytes)
PROGRAM: [=         ]   5.1% (used 13292 bytes from 262144 bytes)
Configuring upload protocol...
AVAILABLE: cmsis-dap, jlink, mbed
CURRENT: upload_protocol = mbed
Looking for upload disk...
Use manually specified: COM3
Uploading .pioenvs\upstream_develop\firmware.bin
*** [upload] COM3\firmware.bin: No such file or directory
 [ERROR] Took 22.56 seconds
```

**Comment by marcbressler** [comment]
Nevermind, was a problem on my end. The board didn't have the proper bootloader
